// Generated by CoffeeScript 1.7.1
(function() {
  window.dictionary = {
    direkt: 'Direktmandat',
    liste: 'Listenmandat',
    Nebentaetigkeit0: 'keine Nebentätigkeiten',
    Nebentaetigkeit: 'Nebentätigkeit',
    Nebentaetigkeit1: 'eine Nebentätigkeit',
    NebentaetigkeitPlural: 'Nebentätigkeiten'
  };

}).call(this);


//# sourceMappingURL=de-de.dict.map
