window.dictionary =
  direkt: 'Direktmandat'
  liste: 'Listenmandat'
  Nebentaetigkeit0: 'keine Nebentätigkeiten'
  Nebentaetigkeit: 'Nebentätigkeit'
  Nebentaetigkeit1: 'eine Nebentätigkeit'
  NebentaetigkeitPlural: 'Nebentätigkeiten'
  'Bündnis 90/Die Grünen': 'Grüne'
  'Die Linke': 'Linke'
  month0: 'Januar'
  month1: 'Februar'
  month2: 'März'
  month3: 'April'
  month4: 'Mai'
  month5: 'Juni'
  month6: 'Juli'
  month7: 'August'
  month8: 'September'
  month9: 'Oktober'
  month10: 'November'
  month11: 'Dezember'
window.abbreviations =
  'Baden-Württemberg': 'BW'
  'Bayern': 'BY'
  'Berlin': 'BE'
  'Brandenburg': 'BB'
  'Bremen': 'HB'
  'Hamburg': 'HH'
  'Hessen': 'HE'
  'Mecklenburg-Vorpommern': 'MV'
  'Niedersachsen': 'NI'
  'Nordrhein-Westfalen': 'NW'
  'Rheinland-Pfalz': 'RP'
  'Saarland': 'SL'
  'Sachsen': 'SN'
  'Sachsen-Anhalt': 'ST'
  'Schleswig-Holstein': 'SH'
  'Thüringen': 'TH'
