window.dictionary =
  direkt: 'Direktmandat'
  liste: 'Listenmandat'
  Nebentaetigkeit0: 'keine Nebentätigkeiten'
  Nebentaetigkeit: 'Nebentätigkeit'
  Nebentaetigkeit1: 'eine Nebentätigkeit'
  NebentaetigkeitPlural: 'Nebentätigkeiten'
  'Bündnis 90/Die Grünen': 'Grüne'
  'Die Linke': 'Linke'
window.abbreviations =
  'Baden-Württemberg': 'BW'
  'Bayern': 'BY'
  'Berlin': 'BE'
  'Brandenburg': 'BB'
  'Bremen': 'HB'
  'Hamburg': 'HH'
  'Hessen': 'HE'
  'Mecklenburg-Vorpommern': 'MV'
  'Niedersachsen': 'NI'
  'Nordrhein-Westfalen': 'NW'
  'Rheinland-Pfalz': 'RP'
  'Saarland': 'SL'
  'Sachsen': 'SN'
  'Sachsen-Anhalt': 'ST'
  'Schleswig-Holstein': 'SH'
  'Thüringen': 'TH'
